services:
  photoframe:
    build: .
    container_name: photoframe-server
    restart: unless-stopped
    ports:
      - "8099:8099"
    volumes:
      - /export/homeassistant/media/ciriolisaver/:/media
      - /export/homeassistant/photoframe-server/web:/web:ro
      - /export/homeassistant/photoframe-server/config.yaml:/config/cameras.yaml:ro
      - /export/homeassistant/photoframe-server/packages:/packages
      - /export/homeassistant/photoframe-server/logs:/logs
      - /export/homeassistant/photoframe-server/thumbnails:/data/thumbnails
    environment:
      - REFRESH=30
      - TITLE=
