services:
  3-bad-dogs:
    build: .
    container_name: 3-bad-dogs-server
    restart: unless-stopped
    ports:
      - "8099:8099"
    volumes:
      - ./config.yaml:/config/config.yaml:ro
      - /path/to/your/photos:/media:ro
